# Generated by Django 2.1.7 on 2019-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='hrcomments',
            field=models.CharField(blank=True, default='', help_text='write something to staff', max_length=255, null=True, verbose_name='Comments'),
        ),
    ]
