# Generated by Django 2.1.7 on 2019-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190402_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Leave days per year counter'),
        ),
    ]
