# Generated by Django 2.1.7 on 2019-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(help_text='upload image size less than 2.0MB', upload_to='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='othername',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Othername (optional)'),
        ),
    ]
