# Generated by Django 2.1.7 on 2019-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190324_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationality'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Religion', 'verbose_name_plural': 'Religions'},
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
    ]
