# Generated by Django 2.1.7 on 2019-03-25 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190324_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Name of Bank')),
                ('account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Account Number')),
                ('branch', models.CharField(blank=True, max_length=125, null=True, verbose_name='Branch')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Starting Salary')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='your biography,tell me something about yourself eg. i love working ...', max_length=255, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contractor', 'Contractor'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='date of employement', null=True, verbose_name='Employement Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir')], default='Mr', max_length=4, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
