# Generated by Django 2.1.7 on 2019-03-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20190325_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True, verbose_name='Fullname')),
                ('tel', models.CharField(max_length=10, null=True, verbose_name='Contact Number')),
                ('location', models.CharField(max_length=125, null=True, verbose_name='Place of residence')),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Niece', 'Niece'), ('Nephew', 'Nephew')], default='Father', help_text='Who is this person to you ?', max_length=8, null=True, verbose_name='Relationship with Person')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-name', '-account'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
    ]
