# Generated by Django 2.1.7 on 2019-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20190325_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], default='Single', max_length=10, null=True, verbose_name='Marital Status')),
                ('spouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse (Fullname)')),
                ('occupation', models.CharField(blank=True, help_text='spouse occupation', max_length=125, null=True, verbose_name='Occupation')),
                ('tel', models.CharField(blank=True, help_text='spouse mobile number', max_length=10, null=True, verbose_name='Tel Number')),
                ('children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Children')),
                ('father', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's Name")),
                ('foccupation', models.CharField(blank=True, max_length=125, null=True, verbose_name="Father's Occupation")),
                ('mother', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's Name")),
                ('moccupation', models.CharField(blank=True, max_length=125, null=True, verbose_name="Mother's Occupation")),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior', 'Senior High School'), ('Junior', 'Junior High School'), ('Primary', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('Other', 'Other')], default='Senior', help_text='highest educational standard ie. your last level of schooling', max_length=8, null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastwork',
            field=models.CharField(blank=True, help_text='where was the last place you worked ?', max_length=125, null=True, verbose_name='Last Place of Work'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='what position where you in your last place of work ?', max_length=255, null=True, verbose_name='Position Held'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssnitnumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SSNIT Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tinnumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TIN Number'),
        ),
    ]
