# Generated by Django 2.1.7 on 2019-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190325_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='fullname',
            field=models.CharField(help_text='who should we contact ?', max_length=255, null=True, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image'),
        ),
    ]
