# Generated by Django 2.1.7 on 2019-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20190325_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', upload_to='profiles', verbose_name='Profile Image'),
        ),
    ]
