# Generated by Django 2.1.7 on 2019-03-25 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0016_auto_20190325_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior', 'Senior High School'), ('Junior', 'Junior High School'), ('Primary', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('O-LEVEL', 'OLevel'), ('Other', 'Other')], default='Senior', help_text='highest educational standard ie. your last level of schooling', max_length=8, null=True, verbose_name='Education'),
        ),
    ]
