# Generated by Django 2.1.7 on 2019-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20190325_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Employee ID Number'),
        ),
    ]
