# Generated by Django 2.1.7 on 2019-03-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted'),
        ),
    ]
