# Generated by Django 2.1.7 on 2019-03-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_employee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dateissued',
            field=models.DateField(help_text='date staff id was issued', null=True, verbose_name='Date Issued'),
        ),
    ]
