# Generated by Django 2.1.7 on 2019-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employee_dateissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='button to toggle employee block and unblock', verbose_name='Is Blocked'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tinnumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TIN'),
        ),
    ]
