# Generated by Django 2.1.7 on 2019-03-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20190326_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contractor', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
    ]
