# Generated by Django 2.1.7 on 2019-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20190326_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='location',
            field=models.CharField(max_length=125, null=True, verbose_name='Place of Residence'),
        ),
    ]
