# Generated by Django 2.1.7 on 2019-03-27 15:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20190327_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Fiancee', 'Fiancee'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Son', 'Son'), ('Daughter', 'Daughter')], default='Father', help_text='Who is this person to you ?', max_length=8, null=True, verbose_name='Relationship with Person'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, null=True, verbose_name='Contact Number'),
        ),
    ]
