# Generated by Django 2.1.7 on 2019-03-27 15:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_auto_20190327_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+233240000000', help_text='Enter number with Country Code Eg. +233240000000', max_length=128, verbose_name='Phone Number (Example +233240000000)'),
        ),
    ]
