# Generated by Django 2.1.7 on 2019-03-29 10:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20190328_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='++233240000000', help_text='Phone Number of Next of Kin', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='nextofkin',
            field=models.CharField(help_text='fullname of next of kin', max_length=255, null=True, verbose_name='Next of Kin'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Fiancee', 'Fiancee'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Son', 'Son'), ('Daughter', 'Daughter')], default='Sister', help_text='Who is this person to you ?', max_length=8, null=True, verbose_name='Relationship with Next of Person'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.CharField(help_text='employee account number', max_length=30, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, help_text='which branch was the account issue', max_length=125, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(help_text='select employee(s) to add bank account', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=125, null=True, verbose_name='Name of Bank'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='This is the initial salary of employee', max_digits=16, null=True, verbose_name='Starting Salary'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Children'),
        ),
    ]
