# Generated by Django 2.1.7 on 2019-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_auto_20190329_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior High', 'Senior High School'), ('Junior High', 'Junior High School'), ('Primary Level', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('O-LEVEL', 'OLevel'), ('Other', 'Other')], default='Senior High', help_text='highest educational standard ie. your last level of schooling', max_length=20, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=4, null=True, verbose_name='Title'),
        ),
    ]
