# Generated by Django 2.1.7 on 2019-04-01 10:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20190330_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', upload_to='profiles', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssnitnumber',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='SSNIT Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tinnumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number of Next of Kin', max_length=128, null=True, verbose_name='Next of Kin Phone Number (Example +233240000000)'),
        ),
    ]
