# Generated by Django 2.1.7 on 2019-04-02 15:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_auto_20190401_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number of Next of Kin', max_length=128, null=True, verbose_name='Next of Kin Phone Number (Example +233240000000)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Enter number with Country Code Eg. +233240000000', max_length=128, null=True, verbose_name='Spouse Phone Number (Example +233240000000)'),
        ),
    ]
