# Generated by Django 2.1.7 on 2019-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_auto_20190408_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Bono', 'Bono'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('North East', 'Northen East'), ('Northen', 'Northen'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Western North', 'Western North'), ('Western', 'Western')], default='Greater Accra', help_text='what region of the country(Ghana) are you from ?', max_length=20, null=True, verbose_name='Region'),
        ),
    ]
